version: '3'
services:
  #apache:
  #  # /usr/local/apache2/conf   -- configurare apache http.conf
  #  container_name: glp_apache
  #  image: httpd
  #  depends_on:
  #    - php
  #    - mysql
  #  networks:
  #    - backend
  #    - frontend  
  #  volumes:
  #    - ../finalf/:/usr/local/apache2/htdocs/finalf
  #    #- ../finalf/:/var/www/html/
  #  ports:
  #    - 8080:80      
  #  restart: always
  #  security_opt:
  #    - seccomp:unconfined  
  mysql:    
    container_name: glp_mysql
    image: gavriladocker/mysql:latest
    networks:
      - backend
    ports: 
      - 3308:3306
    security_opt:
        - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: paull
      MYSQL_USER: root
    volumes:
        - ../mysql_database:/var/lib/mysql
  php:    
    container_name: glp_php_apache
    image: gavriladocker/php:withzip
    #command: ["ls"]
    tty: true
    ports:
      #- 8000:80
      - 443:443            
    networks:
      - backend
    volumes:
      - ../finalf/:/var/www/html/finalf
      - ../confhttpd:/etc/apache2/sites-enabled    
networks:
  # frontend:
  backend:      